spring:
  datasource:
    hikari:
      username: root
      password: ${mysql-password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${ip}:3306/spring_security_demo

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: INFO
        jdbc: INFO