spring:
  application:
    name: spring-security-demo
  profiles:
    active: local
  security:
    user:
      name: justin
      password: 123
      roles: USER

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: trace