spring:
  datasource:
    username: root
    password: ${mysql-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/spring_security_demo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: TRACE
        jdbc: INFO
        jpa: INFO