spring:
  application:
    name: spring-security-demo
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: INFO
        jdbc: INFO