apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-practice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-end-practice
  template:
    metadata:
      labels:
        app: back-end-practice
    spec:
      containers:
        - name: back-end-practice
          image: justinzhang7183/fullstack-backend-practice
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: back-end-practice
  namespace: default
spec:
  type: NodePort
  selector:
    app: back-end-practice
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30301