apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-tool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-end-tool
  template:
    metadata:
      labels:
        app: back-end-tool
    spec:
      containers:
        - name: back-end-tool
          image: justinzhang7183/fullstack-backend-tool
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: back-end-tool
  namespace: default
spec:
  type: NodePort
  selector:
    app: back-end-tool
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30302