spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8000/oauth2/introspect
          client-id: client
          client-secret: secret
  cloud:
    gateway:
      routes:
        - id: tool-server
          uri: lb://tool-server
          predicates:
            - Path=/tool/**

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security:
          oauth2: trace
