spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000
  cloud:
    gateway:
      routes:
        - id: tool-server
          uri: lb://tool-server
          predicates:
            - Path=/tool/**

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security:
          oauth2: trace
