#name: fullstack-backend-ci
#
#on:
#  push:
#    branches:
#      - "master"
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v3
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      -
#        name: Build and push practice module
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: back-end-practice/docker/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-backend-practice:latest
#      -
#        name: Build and push tool module
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: back-end-tool/docker/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-backend-tool:latest
#  deployment:
#    runs-on: self-hosted
#    needs: build
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v3
#      -
#        name: deploy practice module in k8s
#        working-directory: .
#        run: |
#          kubectl delete -f k8s/back-end-practice.yml
#          kubectl apply -f k8s/back-end-practice.yml
#      -
#        name: deploy tool module in k8s
#        working-directory: .
#        run: |
#          kubectl delete -f k8s/back-end-tool.yml
#          kubectl apply -f k8s/back-end-tool.yml
